# docker-compose.override.yml
# Automatically used in local development (docker-compose up)
# For production, use: docker-compose -f docker-compose.yml up

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Mount code for live development
      - ./:/var/www
      - ./storage:/var/www/storage
      - ./bootstrap/cache:/var/www/bootstrap/cache
    environment:
      # Development environment variables
      APP_ENV: local
      APP_DEBUG: "true"
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal
      PLAYWRIGHT_BROWSERS_PATH: /root/.cache/ms-playwright
      # Allow OPcache to detect file changes in dev
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
      PHP_OPCACHE_REVALIDATE_FREQ: "0"

  # Keep separate nginx for local development
  nginx:
    image: nginx:alpine
    container_name: lords-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
