# docker-compose.override.yml
# Automatically used in local development (docker-compose up)
# For production, use: docker-compose -f docker-compose.yml up

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /var/www
    volumes:
      # Mount code for live development
      - ./:/var/www
    environment:
      # Development environment variables
      APP_ENV: local
      APP_DEBUG: "true"
      OCTANE_SERVER: frankenphp
      OCTANE_HTTPS: "false"
      LARAVEL_STORAGE_PATH: /var/www/storage
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal
      PLAYWRIGHT_BROWSERS_PATH: /root/.cache/ms-playwright
      # Allow OPcache to detect file changes in dev
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
      PHP_OPCACHE_REVALIDATE_FREQ: "0"
